Companies list front-end
doanhtu07/Stock_Project pull request #80
Opened 2020-09-26 14:39 UTC by Legacy107

2020-09-27 03:59 UTC, doanhtu07 requested changes
- Cần thay đổi một số thứ trong cái table của company list
   + Mấy cái chữ heading trong bảng: Name, Code, ... nó hơi to
   + Lúc tui hover sao nó có màu đen thế, ông chuyển nó thành màu theme.palette.succeed.tableSorted và theme.palette.succeed.tableSortIcon
- Đối với mỗi item trong cái list, ông cho phép người dùng ấn lên cả cái item, chứ đừng chỉ nhấn cái tên không. 
- Sửa các warning trong mấy file này:
   + ./src/components/Table/CompaniesListTable/VirtualizedTable.js
   + ./src/components/Dialog/UploadFileDialog.js
   + ./src/components/CompanyDetail/DatePickerHistory.js
   + ./src/components/Table/CompaniesListTable/CompaniesListTable.js
   + ./src/components/CompanyDetail/SharePriceTableContainer.js
- Sao có mấy node_modules ông đụng nhầm à?

2020-09-27 03:59 UTC, doanhtu07 commented on front-end/src/pages/Main/Companies.js
> +  getMarketCap = (value) => {
Ông nên chú thích thêm tại sao ông lại mũ 4 ở đây để dễ hiểu hơn.

2020-09-27 03:59 UTC, doanhtu07 commented on front-end/src/pages/Main/Companies.js
> +      marketCapFilter: this.getMarketCap(marketCap),
Cái này ông dùng trong Util dưới dạng một array mà đúng không? Function này trả về số chứ đâu phải array.

2020-09-27 04:08 UTC, Legacy107 commented on back-end/prisma/schema.prisma
> +  lastPrice   Float?
Này do nó auto merge ông. Tui không đụng gì vào file này hết

2020-09-27 04:16 UTC, doanhtu07 commented on back-end/prisma/schema.prisma
> +  lastPrice   Float?
Oh ok thôi vậy ông xoá cái này đi.

2020-09-27 17:09 UTC, doanhtu07 requested changes
- [ ]  Đối với cái bảng company list thì dòng to dòng nhỏ, ông chỉnh thành fixed height. Những tên dài quá thì cho nó "..." ở đằng sau. TextField của material ui nó có wrap noWrap tui nhớ vậy
- [ ]  Trên mobile, mấy cái component trong filter nằm lệch. Ông chỉnh lại nhá. Kiểu như trên màn hình rộng thì để mấy field dàn ra rộng. Theme.breakpoints từ xs trở xuống thì là mỗi field nhỏ lại.
- [ ] Các cột trong table có vẻ không thẳng với table heading
- [ ] Table Heading ông cho chữ nó nhỏ lại tí 
- [ ] Sector và Industry chưa liệt kê ra hết. Có vẻ doc của FMP ghi thiếu. Ông tìm xem có API FMP liệt kê ra hết sector và industry không. Tui cũng sẽ hỏi bên FMP.
- [ ] Nếu ông muốn optimize cái mà get data á thì có một cách: Đó là cache lại các dữ liệu. Cache trong redis theo dạng ghi sau đây. Nhưng ông nên làm Separated Page trước nếu được. Cái optimize này tui sẽ đưa vào hàng đợi task. 
- KEY (email|companiesList|filterString) -> VD cho filterString ông có thể xem parseRedisTransactionsHistoryFilters trong low-dependency/ParserUtil 
- VALUE: List các thông tin của các companies được lưu dưới dạng String. Sau đó, để ở đầu hoặc cuối item một cái item chứa timestamp.  
- Cách hoạt động: Lúc nhấn Reload thì check cache -> Khi check cache nếu có, sẽ check timestamp coi lố qua 5 hay 10 phút hay một lượng thời gian nhất định. Nếu vượt thì gọi lên FMP, cache lại, và gửi result. Nếu không vượt thì lấy cache gửi đi luôn.
- Ông lưu lại chừng 5 cái KEY cache với các filterString các nhau.
- [ ] Sort ông sort theo Name thứ tự là a b c ... nhá. Cái sort Name hình như nó hoạt động chưa đúng.
- [ ] Ông để default sort là theo code từ A xuống đi. 
- [ ] Nãy tui vừa check lại thấy lúc cái trang /companies mount thì nó lấy được dữ liệu từ FMP nhưng data không hiện lên bảng. Phải nhấn vào order thì mới hiện lên. Không biết ông có bị không?

2020-09-29 23:56 UTC, doanhtu07 requested changes
- [ ] Ông có tới 2 cái DatePickerHistory, một cái trong components/DatePicker một cái trong components/CompanyDetail 
-> Tui không thấy ông dùng DatePickerHistory trong components/DatePicker 
- [ ] Đổi dấu mũi tên trong cái order của table heading -> Mũi tên ra trước tên trừ Name vì Name align left còn mấy cái khác align right 
- [ ] Cái breakpoint nhỏ, tui vẫn thấy mấy cái field bị đè lên nhau
- [ ] Đối với cái khung filter bên tay trái, đối với breakpoint lớn, ông cho nó align center đi. Hiện tại nó nằm hơi lệch

2020-09-29 23:56 UTC, doanhtu07 commented on front-end/src/utils/FinancialModelingPrepUtil.js
> +  sectorFilter: string (FmpHelper.fmpSector),
Ông chỉ FmpHelper nằm ở file nào: front-end/src/components/low-dependency/FmpHelper

2020-10-02 14:18 UTC, doanhtu07 approved these changes
LGTM!

2020-10-02 14:20 UTC, merged