First draft
doanhtu07/Stock_Project pull request #85
Opened 2020-10-08 23:38 UTC by ketphan02

Anh tạo 1 function để lấy single rating, 1 function lấy stock screener theo số lượng, 1 function để lấy mọi ratings, với 1 function để nối với interval (sẽ nối với interval sau).

2020-10-09 21:01 UTC, doanhtu07 requested changes
OK anh, anh sửa đi.

2020-10-09 21:01 UTC, doanhtu07 commented on back-end/utils/top-layer/PhanKiet.js
> +const updateCompaniesRatingsList = (user) => {
- Cái này sửa lại hết logic. Mình sẽ không lưu riêng data trong từng user. Cái companies ratings là dùng chung cho toàn bộ server. Nên hồi nãy em có nói là không cần relation user trong model CompanyRating. 
- Đối với function updateCompaniesRatingsList này, anh update thẳng từng item companyRating trong database không cần thông qua user hay gì hết.

2020-10-10 07:18 UTC, doanhtu07 requested changes

2020-10-10 07:18 UTC, doanhtu07 commented on back-end/utils/top-layer/PhanKiet.js
> +        const StockScreener = getStockScreener(totalCompanies);
Function trả promise getStockScreener được dùng sai cách.
Nó phải là:
getStockScreener(totalCompanies)
.then(stockScreener => {
...
})
...
.catch(err => reject(err));

2020-10-10 07:18 UTC, doanhtu07 commented on back-end/utils/top-layer/PhanKiet.js
> +            ratings.push(getSingleShareRating(stockInfo.symbol));
promise không được viết như thế này. Trong trường hợp này anh sẽ phải dùng:
const tasksList = [ ] ;
Sau đó anh add vào tasksList này các function () => getSingleShareRating(symbol)
Rồi dùng SequentialPromisesWithResultsArray

2020-10-10 07:18 UTC, doanhtu07 commented on back-end/utils/top-layer/PhanKiet.js
> +const updateCompaniesRatingsList = () => {
Phải sửa lại nữa vì em không muốn thấy trong user còn companiesRatings nữa.

2020-10-12 04:21 UTC, doanhtu07 requested changes
Anh sửa trước mấy lỗi em nói đi rồi mình sẽ xem tiếp. Mà anh viết xong anh có thử test mấy function của anh hông?

2020-10-12 04:21 UTC, doanhtu07 commented on back-end/utils/FinancialModelingPrepUtil.js
> +        })
.then(stocksRatingsArray => resolve(stocksRatingsArray))

2020-10-12 04:21 UTC, doanhtu07 commented on back-end/utils/FinancialModelingPrepUtil.js
> +        return Promise.all(getRatingsArrayPromise);
bỏ cái này đi

2020-10-12 04:21 UTC, doanhtu07 commented on back-end/utils/FinancialModelingPrepUtil.js
>  module.exports = {
export luôn getSingleShareRatingFromFMP và getStockScreenerFromFMP

2020-10-12 04:21 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +const { SequentialPromisesWithResultsArray } = './low-dependency/PromisesUtil';
thiếu require

2020-10-12 04:21 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +const { getFullStockRatingsFromFMP } = './FinancialModelingPrepUtil.js'
thiếu require

2020-10-12 04:21 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +        const updateCompaniesRatingPromise = getFullStockRatingsFromFMP((allSharesRatings) =>
- vẫn là lỗi giống nãy ở file FinancialModelingPrep. Anh hông cần khai báo updateCompaniesRatingPromise này nha.
- getFullStockRatingsFromFMP là Promise chứ không phải callback

2020-10-12 04:21 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +                    prisma.companiesRatings.findMany({
Vì symbol của anh là @unique rồi nên anh có thể dùng findOne ở đây.

2020-10-12 04:21 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +                        if (isEmpty(shareRatingPrisma))
Khi dùng findOne thì nếu hông tìm thấy nó sẽ trả về null. Anh có thể if(shareRatingPrisma)

2020-10-12 04:21 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +                            return prisma.companiesRatings.create({
- prisma.companiesRatings sai nha anh. 
- prisma.companyRating mới đúng

2020-10-12 04:21 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +                            return prisma.companies.update({
- prisma.companies sai
- prisma.companyRating mới đúng

2020-10-15 21:02 UTC, doanhtu07 requested changes
Anh sửa mấy cái em nói đi

2020-10-15 21:02 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +        getFullStockRatingsFromFMP((allSharesRatings) =>
getFullStockRatingsFromFMP là Promise chứ hông phải callback. Anh đang viết theo cách viết của callback.

2020-10-15 21:02 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +            resolve("Successfully update companies' ratings");
Anh bỏ dấu ' ngay chữ companies đi

2020-10-15 21:38 UTC, ketphan02 reviewed
Cái này là do anh fetch master ở trên github quên check lại

2020-10-16 00:15 UTC, doanhtu07 requested changes
OK. Anh sửa thêm chút nữa là được. Mà anh có chạy thử cái code này chưa. Test tất cả function mà anh viết?

2020-10-16 00:15 UTC, doanhtu07 commented on back-end/utils/FinancialModelingPrepUtil.js
> +                if (shareSymbolString !== "MSF.BR") reject(new Error("Share symbol does not exist."));
Cái if này anh nên để ra chỗ khác (ra ngoài if (isEmpty(stockRatingJSON))) do hai cái if statement này hông liên quan đến nhau lắm.

2020-10-16 00:15 UTC, doanhtu07 commented on back-end/utils/FinancialModelingPrepUtil.js
> +      .then((stockScreenerArray) =>
Sửa tên lại thành stockRatingsArray

2020-10-16 00:15 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +        .then((stockRatingsArray) =>
Sửa tên lại thành finishedUpdatingAllCompanyRatings

2020-10-16 00:15 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +                                    symbol: shareRatingPrisma[0].symbol
shareRatingPrisma thôi không cần [0] do anh đang dùng findOne.

2020-10-16 00:15 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +                    .catch(err => reject(err));
Em hông nghĩ là cần catch ở đây do cái SequentialPromises của mình sẽ handle và catch error ở cuối nếu có.

2020-10-16 11:19 UTC, Legacy107 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +            resolve("Successfully update companies' ratings");
Sao phải bỏ dấu ' vậy :V

2020-10-16 13:23 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +            resolve("Successfully update companies' ratings");
Oh có vẻ tui đọc nhầm rồi. Nếu ông muốn, ông có thể comment sửa lại.

2020-10-16 15:06 UTC, ketphan02 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +            resolve("Successfully update companies' ratings");
Okay vậy anh sẽ thêm lại dấu '

2020-10-29 17:14 UTC, doanhtu07 requested changes
1. Thêm vào index back-end phần // other APIs: 
app.use("/companyRating", require("./routes/companyRating"));

2. Anh chỉ lấy 20 company thôi á? Nếu vậy thì anh sửa note của function getStockScreenerFromFMP lại

2020-10-29 17:14 UTC, doanhtu07 commented on back-end/utils/FinancialModelingPrepUtil.js
> +        .then((stockRating) => stockRating.json())
Thêm chữ return cho nó chuẩn bài anh.

2020-10-29 17:14 UTC, doanhtu07 commented on back-end/utils/FinancialModelingPrepUtil.js
> +        {
cho dấu { này lên dòng bên trên kế bên =>

2020-10-29 17:14 UTC, doanhtu07 commented on back-end/utils/FinancialModelingPrepUtil.js
> +          SequentialPromisesWithResultsArray(tasksList)
Ở đây anh return SequentialPromises...
Rồi thêm một knot then nữa

2020-10-29 17:14 UTC, doanhtu07 commented on back-end/utils/FinancialModelingPrepUtil.js
> +const getFullStockRatingsFromFMP = () =>
Anh note là anh lấy bao nhiêu company ở đây và anh lấy bằng cách nào. Kiểu như lấy 20 company và dùng stock screener limit của FMP (có nghĩa là các company trả về đã được sắp xếp descending theo market cap)

2020-10-29 17:14 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +            SequentialPromisesWithResultsArray(tasksList)
return SequentialPromises...
Rồi thêm một knot then

2020-11-09 07:13 UTC, doanhtu07 requested changes

2020-11-09 07:13 UTC, doanhtu07 commented on back-end/index.js
> +*/
Cái này em để dạng comment để hông phải cứ mỗi lần save changes ở back-end là nó lại chạy lệnh này do cost hơi nhiều API. Nếu sửa được cái em nói ở dưới thì anh hãy uncomment dòng này.

2020-11-09 07:13 UTC, doanhtu07 commented on back-end/index.js
> +// updateCompaniesRatingsList();
Sửa xong cái dưới em nói thì uncomment cái này.

2020-11-09 07:13 UTC, doanhtu07 commented on back-end/index.js
> +  // setInterval(() => updateCompaniesRatingsList(), oneDay);
Sửa xong cái dưới thì uncomment dòng này.

2020-11-11 16:55 UTC, doanhtu07 requested changes
- Sao anh xoá package.json của back-end?

2020-11-11 16:55 UTC, doanhtu07 commented on back-end/utils/PrismaCompanyRatingUtil.js
> +        const forceUpdate = false;
Anh phải cho developer pass vào parameter forceUpdate.

2020-11-11 23:04 UTC, doanhtu07 approved these changes
LGTM!

2020-11-11 23:05 UTC, merged